### ISSUE TITLE
An error occured while spraying credentials: ''NoneType' object has no attribute 'error_code'

### ISSUE THREAD

**Issue by iknowjason** [MarkoH17/Spray365#2]
Getting this error right after "Authentication Success" for a valid M365 user in the tenant:  
ERROR]: An error occured while spraying credentials:  ' 'NoneType' object has no attribute 'error_code'

I'll try to debug this in the code for why this is happening.  When I proxy the request through Burp Suite it shows a successful OAuth code flow with a bearer token response.  So authentication is working, but it might be an issue with parsing the response.  Don't know why the code is looking for an "error_code" when it is a success. 

This looks like a great tool @MarkoH17 - thanks for the contribution.

**Comment by MarkoH17** [comment]
@iknowjason 

I was able to reproduce the issue and I believe it has been fixed with 96cf8f39afa1aa1944c5c433187c0ddfe1673afa. Can you pull the latest version and see if the issue persists?

Thanks for the bug report!

**Comment by iknowjason** [comment]
Oops, I just submitted a PR for this after debugging for a while.  I'll check it out as soon as I can.

**Comment by iknowjason** [comment]
@MarkoH17 

I pulled the latest and it is fixed.  Thanks.  Been testing a lot of spraying tools and this one is nice.  I like the novel approach of generating an execution plan.  Keep up the good work.

I'll close the issue and my PR.

Jason
