### ISSUE TITLE
Spraying Stopped due to Error

### ISSUE THREAD

**Issue by vysecurity** [MarkoH17/Spray365#5]
Hi there,

Sometimes it happens, but not always. I get an error that stops the spraying.

```
An error occured while spraying credentials: 'Unable to get authority configuration for https://login.microsoftonline.com/organizations. Authority would typ
 https://login.microsoftonline.com/your_tenant_name'
```

**Comment by MarkoH17** [comment]
Hey @vysecurity ,

Can you share the domain you encountered this error on? I've seen the same error a time or two, and I recall the issue being something specific with the ADFS / AAD configuration on the domain. I'd like to troubleshoot this a bit more.

**Comment by vysecurity** [comment]
Actually, it was with Spray365, but I think the connection timed out and it wouldn't retry automatically and just exit.

**Comment by MarkoH17** [comment]
At this time, I don't plan on adding a retry on network error feature. Feel free to open a PR if you'd like to contribute. In the meantime, I am going to close this issue.
